### ISSUE TITLE
Difficulty overriding margins on buttons

### ISSUE THREAD

**Issue by Guillaume-Docquier** [sharegate/semantic-ui-sg#12]
Semantic styles it's buttons with .ui.button to set a default margin-right of 4px. This makes it impossible to override it using frameworks like Tachyons.

![image](https://user-images.githubusercontent.com/16602209/49830753-12dd9780-fd60-11e8-9f95-46dde24d7898.png)

**Comment by fraincs** [comment]
default button spacing is now 0px on 2.2.1
