### ISSUE TITLE
Disabled button cannot be overridden

### ISSUE THREAD

**Issue by joseph-passineau** [sharegate/semantic-ui-sg#14]
Button can be overridden easily, but not the disabled button. They have !imporant on all properties.
![image](https://user-images.githubusercontent.com/16294504/50841377-988a3e00-1332-11e9-8c25-4f4c606877a4.png)

**Comment by fraincs** [comment]
What is your use case, do you need a variant?

**Comment by joseph-passineau** [comment]
Yes. Our case was that the disable button would have a different color. We opted instead for a div that looked like a button, but wasn't one. This was ok because the button in question would never really be enabled.

**Comment by fraincs** [comment]
Closing since it's a design issue.
