### ISSUE TITLE
Support Input with custom icon and custom position

### ISSUE THREAD

**Issue by patricklafrance** [sharegate/semantic-ui-sg#18]
https://react.semantic-ui.com/elements/input/#variations-icon-position

https://react.semantic-ui.com/elements/input/#variations-icon-position

**Comment by fraincs** [comment]
Can you provide a code sample as well as the result

**Comment by patricklafrance** [comment]
Avec un custom icon comme dans la doc ici: https://react.semantic-ui.com/elements/input/#variations-icon-element

**Comment by fraincs** [comment]
> Avec un custom icon comme dans la doc ici: https://react.semantic-ui.com/elements/input/#variations-icon-element

try this 

<Input iconPosition="left" icon={<Icon name="search" />} placeholder="Search..." />

**Comment by patricklafrance** [comment]
My bad I was trying to use a custom SVG icon, closing!
