### ISSUE TITLE
Hover on options is red when select is in error state

### ISSUE THREAD

**Issue by kingbaub3** [sharegate/semantic-ui-sg#19]
**Description**
When the select component is in error state, the hover effect on its options is red too. This gives the impression to the user that no options is valid, which is not the case. 

**Expected behavior**
The hover on options should remain the same even if the select in is error state.

![image](https://user-images.githubusercontent.com/6119223/55811701-88136c00-5ab7-11e9-8a89-46389c007a5b.png)

**Comment by fraincs** [comment]
This is ok
