### ISSUE TITLE
Weird Circular Badges sizing behaviors

### ISSUE THREAD

**Issue by AlexandreArpin** [sharegate/semantic-ui-sg#25]
Hi,

Overcast is having some issues with the circular badges.

It seems rules for normal labels are being mixed with circular badges, leading in unexpected sizing behavior.

*Actual Behavior*
![image](https://user-images.githubusercontent.com/3902349/56853834-f7cc8800-68fa-11e9-97c8-d7917bd38a58.png)

*Sort of Expected*
![image](https://user-images.githubusercontent.com/3902349/56853881-c99b7800-68fb-11e9-9182-52619f4bbd10.png)

Is the size jump between mini -> massive supposed to be constant? (Like, jump of 4 everytime?)

**Comment by fraincs** [comment]
No discussions yet with designers, this explains the weird behaviour. One could argue to release something consistant until further advice.

**Comment by AlexandreArpin** [comment]
3dc03f006b4e139779d8f66dd8a48ebe56692e7c fixed the issue!
