### ISSUE TITLE
The inverted tooltip is missing the caret

### ISSUE THREAD

**Issue by Guillaume-Docquier** [sharegate/semantic-ui-sg#8]
![image](https://user-images.githubusercontent.com/16602209/49814870-82d82780-fd38-11e8-8600-9477eee20b78.png)

The non inverted version has one
![image](https://user-images.githubusercontent.com/16602209/49814905-92577080-fd38-11e8-88f1-53bdddd2e142.png)

**Comment by fraincs** [comment]
Basic tooltips do not have a carret. See https://semantic-ui.com/modules/popup.html
